# Generated by Django 5.0.7 on 2024-07-14 12:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
