# Generated by Django 5.0.7 on 2024-07-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_staticpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
