# Generated by Django 5.0.7 on 2024-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='content-imgs'),
        ),
    ]
