# Generated by Django 5.0.7 on 2024-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='content-imgs'),
        ),
    ]
