# Generated by Django 5.0.7 on 2024-07-14 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_genre_content_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='Content_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='content',
            name='genre',
        ),
        migrations.AlterField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Content_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Contents', to='content.tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='Genres', to='content.genre'),
        ),
    ]
