# Generated by Django 5.0.7 on 2024-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_content_dislikes_remove_content_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='Genres', to='content.genre'),
        ),
    ]
